= *paulojeronimo.com*
Paulo Jerônimo
v1.0.0, {localdatetime}: 15 km running challenger
:source-highlighter: coderay
:stylesdir: css
:linkcss:
:icons: font
:imagesdir: images
:nofooter:
:docinfo2:
include::uris-and-attributes.adoc[]
:og-description: Home page

include::icons.adoc[]

[.left.text-center.rounded]
image::{og-image}[width=40%]

Hi! *[red]#My name is {author}#*.

.*About this website* _(click to details)_...
[%collapsible]
====
It is a *straightforward website*, almost entirely text-based and
written in {uri-what-is-asciidoc}[AsciiDoc format^]), {Bash} and a few
scripts in {JavaScript}.
These are the programming languages that I am currently using most of my
time.
[green]#{uri-pj-github-website}[Here is the code of this site^] if you
are interested in it#.

Note that in the icons above you can see links to all my blog posts (
{BlogPostsIcon1x} ), code ( {GitHubIcon1x} ), articles, and tutorials (
{SitemapIcon1x} ), that I've written.

I have link:english-videos.html#yt-20221222[a video where I'm presenting
a version of this website] on YouTube (2022, Dec 22).
====

.I am a *{SoftwareDeveloper}/ {TechnicalLeader}*
****
I have experience in *{uri-pj-sitemap}/#tags[several technologies^]* and
more than two decades (since 1993) working in positions like
*{SoftwareDeveloper}*, *{SoftwareArchitect}*, and *{TechnicalLeader}*.
I can also work as a *{DevOpsEngineer}* guy because I have
{uri-pj-resume-devops}[many years of giving practical solutions in this
area], automating tasks in private or public {uri-cloud-platforms}[cloud
platforms^] or data centers.

My bachelor's degree in *Computer Science* was in 1994, and in 2002 I
concluded a specialization in *Distributed Systems and Object
Orientation*.

I always work with *{security}* and *{quality}* in mind.
My software is *{TestInfected}* since I met {KentBeck} in person during
the {uri-xpbrasil2002}[Extreme Programming Brasil event in 2002^].

*I am {uri-open-to-job}[open to job opportunities^] as a
{FullStackDeveloper} or {DevOpsAndSRE}*.
_[red]#Please, click on the links to see my customized résumés for each
position!#_
I can work full or part-time.
****

.I founded the project *Finisher.Tech*, focusing on *Blockchain/ Web3 development* ...
[%collapsible]
====
{FinisherTech} started with my entrepreneurial spirit in the wellness
area and was {uri-finishertech-project}[a project^], but it is now the
name of my Brazilian company.

[[web3]]
*With my current focus on {Blockchain} and {Web3} development*, I'm
inviting people (from all places of the world) to work with me in a
*Distributed Autonomous Organization (DAO)* that I initiated with the
name {FinishersDAO}.
This DAO is focused on developing Web3 software for the wellness area in
a category called {MoveToEarn}.
Beyond this focus, by inviting people to join me in this DAO, one of my
interests is to share knowledge while improving programming skills for
the new Web era.
====

.Currently, *I live in Brazil* with my wife ...
[%collapsible]
====
{uri-pj-wife}[We^] got married {uri-pj-marriage-photo}[in 1997^] and
now have two adults child ({uri-pj-daughter}[a married daughter^] and
{uri-pj-son}[a son^]).
My home is in {Brasilia}, but I also spend many weeks of the year in
{RioDeJaneiro} because my son lives there.
====

.I'm an *Amateur Triathlete (3x Ironman)* ...
[%collapsible]
====
\... practicing sports *daily* to get more healthy and quality life. +
You can read {uri-saudeecripto-com}[my history in Ironman races^] _(only
in Brazilian Portuguese now)_ and {uri-saudeecripto}[other related
links^]. +
[[remark]] After a stop in my workouts, today, I'm a *-> {revremark} <-*
{uri-finishersdao-desafio1}[(read more about this)^].
====
