= *paulojeronimo.com*
Paulo Jerônimo
v1.0.0, {localdatetime}: 15 km running challenger
:source-highlighter: coderay
:stylesdir: css
:linkcss:
:icons: font
:imagesdir: images
:nofooter:
:docinfo2:
include::uris-and-attributes.adoc[]
:og-description: Home page

include::icons.adoc[]

[.left.text-center.rounded]
image::{og-image}[width=40%]

Hi! *[red]#My name is {author}#*.

.{uri-pj-website-video}[Here's a video where I'm presenting a version of this website^] __(uncollapse to details)__ ...
[%collapsible]
====
It is a *straightforward website*, almost entirely text-based and
written in {uri-what-is-asciidoc}[AsciiDoc format^]), {Bash} and a few
scripts in {JavaScript}.
These are the programming languages that I am currently using most of my
time.
[green]#{uri-pj-github-website}[Here is the code of this site^] if you
are interested in it#.

Note that in the icons above you can see links to all my blog posts (
{BlogPostsIcon1x} ), code ( {GitHubIcon1x} ), articles, and tutorials (
{SitemapIcon1x} ), that I've written.
====

.I'm an Entrepreneur and a *Software Architect/ Developer*
****
I have {uri-pj-sitemap}/#tags[knowledge of many technologies^] and more
than two decades of experience in software architecture and development.
I have been a programmer {uri-pj-cv-1993}[since 1993^].
My bachelor's degree in Computer Science was in 1994, and in 2002 I
concluded a {uri-pj-resume-specialist}[specialization in Distributed
Systems and Object Orientation^].
I am always working with *{security}* in mind.
I also work as a *{DevOps}* guy because I like automating tasks in
private or public {uri-cloud-platforms}[cloud platforms^] or data
centers.

*[blue]#I am {uri-open-to-job}[open to job opportunities^] as a
{FullStackDeveloperWeb3} or {DevOpsEngineer}#*.
_[red]#Please, click on the links to see my customized résumés for each
position!#_
I can work full or part-time.
****

.As an Entrepreneur, I founded the project *Finisher.Tech* ...
[%collapsible]
====
{FinisherTech} started as {uri-finishertech-project}[a project^]
but is now the name of my Brazilian company.

[[web3]]
*Also, [red]#with my current focus on {Web3} technologies#*, I'm
inviting people (from all places of the world) to work with me in a *DAO
(Distributed Autonomous Organization)* that I initiated with the name
{FinishersDAO}.
This DAO is focused on developing Web3 software for the wellness area in
a category called {MoveToEarn}.
Beyond this focus, by inviting people to join me in this DAO, one of my
interests is to share knowledge while improving programming skills for
the new Web era.
====

.Currently, *I live in Brazil* {uri-pj-wife}[with my wife^] ...
[%collapsible]
====
{uri-pj-marriage-photo}[We got married in 1997^] and
now have two adults child ({uri-pj-daughter}[a married daughter^] and
{uri-pj-son}[a son^]).
My home is in {Brasilia}, but I also spend many weeks of the year in
{RioDeJaneiro} because my son lives there.
====

.I'm an *Amateur Triathlete (3x {uri-ironman}[Ironman^])* ...
[%collapsible]
====
\... practicing sports *daily* to get more healthy and quality life. +
You can read {uri-saudeecripto}[my history in Ironman races^] _(only in
Brazilian Portuguese now)_. +
[[remark]] After a stop in my workouts, today, I'm a *-> {revremark} <-*
{uri-finishersdao-desafio1}[(read more about this)^].
====
