= paulojeronimo.com
Page last updated in {localdatetime}
:source-highlighter: coderay
:stylesdir: css
:linkcss:
:icons: font
:nofooter:
:docinfo2:

:uri-pj: https://paulojeronimo.com
:uri-pj-cv: {uri-pj}/cv/en
:uri-pj-resume: {uri-pj}/cv/en/resume.html
:uri-pj-docs: {uri-pj}/docs
:uri-pj-avatar: https://avatars2.githubusercontent.com/u/66204?s=400&v=4
:uri-pj-twitter: https://twitter.com/paulojeronimo
:uri-pj-github: https://github.com/paulojeronimo
:uri-pj-linkedin: https://www.linkedin.com/in/paulojeronimo/
:uri-pj-youtube: https://www.youtube.com/~paulojeronimo
:uri-pj-whatsapp: https://wa.me/5561998073864
:uri-pj-sitemap: {uri-pj}/sitemap
:uri-pj-email: mailto:paulojeronimo@gmail.com
:uri-pj-skype: https://join.skype.com/invite/nepGdOPZU0Nt
:uri-what-is-asciidoc: https://asciidoctor.org/docs/what-is-asciidoc/
:uri-ironman: https://en.wikipedia.org/wiki/Ironman_Triathlon
:uri-finishertech: https://finisher.tech/slides/projeto.A4.9slides.pdf

:pt-br: https://en.wikipedia.org/wiki/Brazilian_Portuguese[pt-br^]

[.text-center]
{uri-pj-email}[icon:envelope[2x]^] |
{uri-pj-whatsapp}[icon:whatsapp[2x]^] |
{uri-pj-skype}[icon:skype[2x]^] |
{uri-pj-linkedin}[icon:linkedin[2x]^] |
{uri-pj-github}[icon:github[2x]^] |
{uri-pj-twitter}[icon:twitter[2x]^] |
{uri-pj-youtube}[icon:youtube[2x]^] |
{uri-pj-sitemap}[icon:sitemap[2x]^]

'''

[.left.text-center.rounded]
image::{uri-pj-avatar}[width=40%]

Hi! *My name is Paulo Jerônimo*.
Welcome to my *very very simple website* (almost completely text-based
and written in {uri-what-is-asciidoc}[AsciiDoc format^]).

I work as a *Software Architect/ Developer* and, sometimes, as a
*DevOps* guy.
I am always working with *[red]#security in mind#*.
I have some skills and many years of experience developing software
(since 1993).

Currently, *I live in Brazil* and in addition to my work as a software
developer, +
*I also founded and maintain a project named
{uri-finishertech}[Finisher.Tech^]*.

I'm an amateur triathlete practicing sports *daily* to get more
healthy and life quality. +
I have finished three (3) *{uri-ironman}[Ironman^]* races.

You can see some of the code, articles, and tutorials that I coded (or
wrote) by accessing the {uri-pj-sitemap}[site map^].
You can also see {uri-pj-resume}[my résumé^] or {uri-pj-cv}[my complete
CV^].

////
https://discuss.asciidoctor.org/Borders-for-images-td1957.html
https://blog.mrhaki.com/2015/04/awesome-asciidoctor-adding-custom.html
https://docs.asciidoctor.org/asciidoctor/latest/docinfo/
////
