= *paulojeronimo.com*
Paulo Jerônimo
v1.0.0, {localdatetime}: -> 15 km running challenger <-
:source-highlighter: coderay
:stylesdir: css
:linkcss:
:icons: font
:nofooter:
:docinfo2:

include::uris-and-attributes.adoc[]

[.text-center]
{uri-pj-email}[icon:envelope[2x]^] |
{uri-pj-whatsapp}[icon:whatsapp[2x]^] |
{uri-pj-skype}[icon:skype[2x]^] |
{uri-pj-linkedin}[icon:linkedin[2x]^] |
{uri-pj-github}[icon:github[2x]^] |
{uri-pj-twitter}[icon:twitter[2x]^] |
{uri-pj-youtube}[icon:youtube[2x]^] |
{sitemapLink}

'''

[.left.text-center.rounded]
image::{uri-pj-avatar}[width=40%]

Hi! *[red]#My name is {author}#*.
Welcome to my *straightforward website* (almost entirely text-based and
written in {uri-what-is-asciidoc}[AsciiDoc format^]).
[green]#{uri-pj-github-website}[Here is the code of this site^] if you
are interested in it#.

.I'm an Entrepeneur and a *Software Architect/ Developer*
****
Sometimes, I also work as a *DevOps* guy.
I am always working with *[red]#security in mind#* (see
{uri-pj-keybase}[my keybase account^]).
I have some skills and many years of experience developing software
(since 1993).

You can also read all about my past works in {uri-pj-resume}[my résumé^]
or {uri-pj-cv}[my complete CV^].
****

Currently, *I live in Brazil* and in addition to my work as a software
developer, +
*I also founded and maintain {uri-finishertech-project}[a project^] (and
now a Brazilian company) named {uri-finishertech}[Finisher.Tech^]*.

[TIP]
====
*[red]#With my current focus on Web3 technologies#*, I'm inviting people
(starting in my country and talking in Portuguese) to work with me in a
*DAO (Distributed Autonomous Organization)* that I initiated with the
name {FinishersDAO}. +
I have plans to invite people from other countries soon (at the
beginning of 2023) to participate in this DAO.
====

.I'm an *Amateur Triathlete (3x {uri-ironman}[Ironman^])* ...
****
\... practicing sports *daily* to get more healthy and life quality. +
Read {uri-saudeecripto}[my history in Ironman races^] _(only in
Brazilian Portuguese at this moment)_. +
[[remark]] After a stop in my workouts, today, I'm a *{revremark}*
{uri-finishersdao-desafio1}[(read more about this)^].
****

You can see some of the code, articles, and tutorials that I coded (or
wrote) by accessing my site map ({sitemapLink}).
