= *paulojeronimo.com*
Paulo Jerônimo
v1.0.0, {localdatetime}: 15 km running challenger
:source-highlighter: coderay
:stylesdir: css
:linkcss:
:icons: font
:imagesdir: images
:nofooter:
:docinfo2:
include::uris-and-attributes.adoc[]
:og-description: Home page

include::icons.adoc[]

[.left.text-center.rounded]
image::{og-image}[width=40%]

Hi! *[red]#My name is {author}#*.
Welcome to my *straightforward website* (almost entirely text-based and
written in {uri-what-is-asciidoc}[AsciiDoc format^]) and {Bash}.
[green]#{uri-pj-github-website}[Here is the code of this site^] if you
are interested in it#.

Note that in the icons above you can see links to all my blog posts (
{BlogPostsIcon1x} ), code ( {GitHubIcon1x} ), articles, and tutorials (
{SitemapIcon1x} ), that I've written.

.I'm an Entrepreneur and a *Software Architect/ Developer*
****
I sometimes work as a *DevOps* guy because I like automating many things
(even in my daily tasks).
I am always working with {uri-pj-keybase}[security in mind^]).
I have {uri-pj-sitemap}[knowledge of many technologies^] and more than
two decades of experience in software architecture and development.
I have been a programmer since 1993.
My bachelor's degree in Computer Science was in 1994, and in 2002, I
concluded a specialization in Distributed Computing.

You can also read about my past works in *my résumé (in
{uri-pj-resume}[English^] or {uri-pj-resume-pt-br}[Brazilian
Portuguese^])*.
****

Currently, *I live in Brazil*.
My current is in {Brasilia}, but I also spend many weeks of the year in
{RioDeJaneiro} because {uri-pedropaulo}[my son^] lives there.

In addition to my work as a software developer, *I founded and
maintained {uri-finishertech-project}[a project^] (now the name of my
Brazilian company) named {FinisherTech}*.

[TIP]
====
*[red]#With my current focus on Web3 technologies#*, I'm inviting people
(from all places of the world) to work with me in a *DAO (Distributed
Autonomous Organization)* that I initiated with the name {FinishersDAO}.
This DAO is focused on developing Web3 software for the wellness area in
a category called {MoveToEarn}.
Beyond this focus, by inviting people to join me in this DAO, one of my
interests is to share knowledge while improving programming skills for
the new Web era.
====

.I'm an *Amateur Triathlete (3x {uri-ironman}[Ironman^])* ...
****
\... practicing sports *daily* to get more healthy and quality life. +
You can read {uri-saudeecripto}[my history in Ironman races^] _(only in
Brazilian Portuguese now)_. +
[[remark]] After a stop in my workouts, today, I'm a *-> {revremark} <-*
{uri-finishersdao-desafio1}[(read more about this)^].
****
